import {
  Box,
  Paper,
  Typography,
  Divider,
  Chip,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Alert,
  useTheme,
} from '@mui/material'
import { useTranslation } from 'react-i18next'
import WarningAmberIcon from '@mui/icons-material/WarningAmber'
import ReportProblemIcon from '@mui/icons-material/ReportProblem'
import HealthAndSafetyIcon from '@mui/icons-material/HealthAndSafety'
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline'
import ScheduleIcon from '@mui/icons-material/Schedule'
import ScienceIcon from '@mui/icons-material/Science'
import type { TriageResult } from '../../types'
import { getSeverityColor } from '../../utils/helpers'

interface TriageResultProps {
  result: TriageResult
}

const URGENCY_META = {
  immediate: { color: '#dc2626', icon: ReportProblemIcon },
  urgent: { color: '#f59e0b', icon: WarningAmberIcon },
  routine: { color: '#10b981', icon: CheckCircleOutlineIcon },
}

export default function TriageResult({ result }: TriageResultProps) {
  const { t } = useTranslation()
  const theme = useTheme()

  const riskColor = getSeverityColor(result.riskLevel)
  const urgencyMeta = URGENCY_META[result.urgency]

  return (
    <Paper
      variant="outlined"
      sx={{
        p: 3,
        borderRadius: 3,
        borderColor: riskColor,
        borderWidth: 2,
      }}
    >
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
        <HealthAndSafetyIcon sx={{ color: riskColor, mr: 1.5, fontSize: 28 }} />
        <Box>
          <Typography fontWeight={700} fontSize={16}>
            {t('reports.triageResult')}
          </Typography>
          <Typography fontSize={12} color="text.secondary">
            Confidence: {Math.round(result.confidenceScore * 100)}%
          </Typography>
        </Box>
      </Box>

      <Box sx={{ mb: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Chip
            label={`${t('reports.riskLevel')}: ${t(
              `status.${result.riskLevel}`,
            )}`}
            sx={{
              bgcolor: `${riskColor}20`,
              color: riskColor,
              fontWeight: 700,
            }}
          />
          <Chip
            icon={<ScheduleIcon />}
            label={`${t('reports.urgency')}: ${t(
              `reports.${result.urgency}`,
            )}`}
            sx={{
              bgcolor: `${urgencyMeta.color}20`,
              color: urgencyMeta.color,
              fontWeight: 700,
            }}
          />
        </Box>
      </Box>

      <Typography
        fontSize={13}
        fontWeight={600}
        color="text.secondary"
        mb={1}
      >
        {t('reports.suspectedDiseases')}
      </Typography>
      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, mb: 2 }}>
        {result.suspectedDiseases.length > 0 ? (
          result.suspectedDiseases.map((disease) => (
            <Chip
              key={disease.diseaseId}
              label={`${disease.name} (${Math.round(disease.probability * 100)}%)`}
              sx={{ fontSize: 12, fontWeight: 600 }}
            />
          ))
        ) : (
          <Typography fontSize={13} color="text.secondary">
            No specific diseases suspected
          </Typography>
        )}
      </Box>

      <Divider sx={{ my: 2 }} />

      <Typography
        fontSize={13}
        fontWeight={600}
        color="text.secondary"
        mb={1}
      >
        {t('reports.recommendedActions')}
      </Typography>
      <List dense disablePadding>
        {result.recommendedActions.map((action, index) => (
          <ListItem key={index} disableGutters sx={{ alignItems: 'flex-start' }}>
            <ListItemIcon sx={{ minWidth: 32 }}>
              <CheckCircleOutlineIcon sx={{ color: 'success.main', fontSize: 18 }} />
            </ListItemIcon>
            <ListItemText
              primary={action}
              primaryTypographyProps={{ fontSize: 13 }}
            />
          </ListItem>
        ))}
      </List>

      {result.note && (
        <Alert severity="info" sx={{ mt: 2, fontSize: 13 }}>
          {result.note}
        </Alert>
      )}

      <Box
        sx={{
          mt: 2,
          pt: 2,
          display: 'flex',
          alignItems: 'center',
          gap: 1,
          borderTop: 1,
          borderColor: theme.palette.divider,
        }}
      >
        <ScienceIcon sx={{ fontSize: 18, color: 'text.secondary' }} />
        <Typography fontSize={12} color="text.secondary">
          Auto-generated by AI triage engine · Review by a veterinarian required
        </Typography>
      </Box>
    </Paper>
  )
}